/**
 * Account
 * Account Api Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GroupMenuDto } from './group-menu-dto';


export interface FeatureGroupDto { 
    id?: number;
    label?: string;
    icon?: string;
    routerLink?: string;
    hasChildren?: boolean;
    parent?: number;
    showInMenu?: boolean;
    orderValue?: number;
    groupMenu?: GroupMenuDto;
}

