/**
 * Account
 * Account Api Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FeatureGroupDto } from './feature-group-dto';
import { ApiResult } from './api-result';


export interface MenuResponse { 
    result?: ApiResult;
    context?: Array<FeatureGroupDto>;
}

