/**
 * Account
 * Account Api Docs
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiResult } from './api-result';
import { MenuTransformedResponseContext } from './menu-transformed-response-context';


export interface MenuTransformedResponse { 
    result?: ApiResult;
    context?: MenuTransformedResponseContext;
}

